#!/bin/bash
# Instrukcje tworzenia hasła aplikacji Google dla sanbud.kontakt@gmail.com

echo "📧 Tworzenie hasła aplikacji Google dla sanbud.kontakt@gmail.com"
echo "================================================================"
echo ""
echo "⚠️  WAŻNE: Musisz to zrobić ręcznie w przeglądarce"
echo ""
echo "Krok 1: Zaloguj się do konta Google"
echo "   🔗 https://myaccount.google.com/"
echo "   👤 Email: sanbud.kontakt@gmail.com"
echo ""
echo "Krok 2: Przejdź do ustawień bezpieczeństwa"
echo "   🔗 https://myaccount.google.com/security"
echo ""
echo "Krok 3: Włącz weryfikację dwuetapową (jeśli nie jest włączona)"
echo "   📍 Znajdź sekcję 'Logowanie w Google'"
echo "   📍 Kliknij 'Weryfikacja dwuetapowa'"
echo "   📍 Postępuj zgodnie z instrukcjami"
echo ""
echo "Krok 4: Utwórz hasło aplikacji"
echo "   🔗 https://myaccount.google.com/apppasswords"
echo "   📍 Wybierz aplikację: 'Poczta'"
echo "   📍 Wybierz urządzenie: 'Inne (nazwa niestandardowa)'"
echo "   📍 Wpisz: 'SanBud SMTP Server'"
echo "   📍 Kliknij 'Generuj'"
echo ""
echo "Krok 5: Skopiuj wygenerowane hasło (16 znaków)"
echo "   ⚠️  Hasło będzie wyświetlone tylko raz!"
echo "   📋 Skopiuj hasło (np: 'abcd efgh ijkl mnop')"
echo "   💾 Zapisz je w bezpiecznym miejscu"
echo ""
echo "Krok 6: Zaktualizuj konfigurację"
echo "   Uruchom: ./scripts/update-smtp-config.sh"
echo "   Lub ręcznie zaktualizuj pliki:"
echo "   - .env (dla lokalnego środowiska)"
echo "   - Azure App Settings (dla produkcji)"
echo ""
echo "================================================================"
echo ""
echo "🔍 Jeśli Google Workspace nie pozwala na hasła aplikacji:"
echo ""
echo "Opcja A: Sprawdź ustawienia administratora"
echo "   1. Zaloguj się do Google Admin Console"
echo "   2. Bezpieczeństwo > Ustawienia > Mniej bezpieczne aplikacje"
echo "   3. Włącz dostęp dla użytkowników"
echo ""
echo "Opcja B: Użyj OAuth2 (bardziej bezpieczne)"
echo "   1. Przejdź do Google Cloud Console"
echo "   2. Utwórz nowy projekt lub wybierz istniejący"
echo "   3. Włącz Gmail API"
echo "   4. Utwórz credentials OAuth 2.0"
echo ""
echo "Opcja C: Użyj alternatywnej usługi email"
echo "   - SendGrid (12,000 emaili/miesiąc za darmo)"
echo "   - Mailgun (5,000 emaili/miesiąc za darmo)"
echo "   - Amazon SES (62,000 emaili/miesiąc za darmo z AWS Free Tier)"
echo ""
echo "================================================================"
echo ""
echo "📞 Potrzebujesz pomocy?"
echo "   Otwórz przeglądarkę na: https://myaccount.google.com/apppasswords"
echo ""

# Otwórz przeglądarkę automatycznie
read -p "Czy chcesz otworzyć Google App Passwords w przeglądarce? (t/n): " choice
if [[ "$choice" == "t" || "$choice" == "T" ]]; then
    if [[ "$OSTYPE" == "darwin"* ]]; then
        open "https://myaccount.google.com/apppasswords"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        xdg-open "https://myaccount.google.com/apppasswords"
    else
        echo "Otwórz ręcznie: https://myaccount.google.com/apppasswords"
    fi
fi