#!/bin/bash
# DNS Configuration Instructions for sanbud24.pl
# This script retrieves DNS records from Azure and displays them

set -e

# Get values from Azure
RESOURCE_GROUP="rg-sanbud-prod"
BACKEND_APP="app-sanbud-api-prod"
FRONTEND_APP="swa-sanbud-frontend-prod"

echo "Retrieving configuration from Azure..."
VERIFICATION_ID=$(az webapp show --name $BACKEND_APP --resource-group $RESOURCE_GROUP --query "customDomainVerificationId" -o tsv 2>/dev/null || echo "[ERROR: Run az login first]")
FRONTEND_URL=$(az staticwebapp show --name $FRONTEND_APP --resource-group $RESOURCE_GROUP --query "defaultHostname" -o tsv 2>/dev/null || echo "[ERROR: Frontend not found]")

echo ""
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║         DNS Records Configuration for sanbud24.pl                 ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Login to your DNS provider panel and add these records"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "DNS RECORDS TO ADD:"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "1. WWW SUBDOMAIN (for www.sanbud24.pl)"
echo "   Type:     CNAME"
echo "   Host:     www"
echo "   Points to: $FRONTEND_URL"
echo "   TTL:      300"
echo ""
echo "2. API SUBDOMAIN (for api.sanbud24.pl)"
echo "   Type:     CNAME"
echo "   Host:     api"
echo "   Points to: $BACKEND_APP.azurewebsites.net"
echo "   TTL:      300"
echo ""
echo "3. AZURE VALIDATION (for Azure verification)"
echo "   Type:     TXT"
echo "   Host:     @"
echo "   Value:    $VERIFICATION_ID"
echo "   TTL:      300"
echo ""
echo "4. API VERIFICATION (for backend verification)"
echo "   Type:     TXT"
echo "   Host:     asuid.api"
echo "   Value:    $VERIFICATION_ID"
echo "   TTL:      300"
echo ""
echo "5. ROOT DOMAIN (sanbud24.pl - Option A: if ALIAS supported)"
echo "   Type:     ALIAS (or ANAME)"
echo "   Host:     @"
echo "   Points to: $FRONTEND_URL"
echo "   TTL:      300"
echo ""
echo "   ROOT DOMAIN (sanbud24.pl - Option B: if only A records supported)"
echo "   FIRST add the TXT record above, then Azure will provide an A record IP"
echo ""
echo "6. EMAIL MX RECORD (optional, for future email)"
echo "   Type:     MX"
echo "   Host:     @"
echo "   Points to: mail.sanbud24.pl"
echo "   Priority: 10"
echo "   TTL:      3600"
echo ""
echo "7. SPF RECORD (optional, for future email)"
echo "   Type:     TXT"
echo "   Host:     @"
echo "   Value:    v=spf1 include:_spf.google.com ~all"
echo "   TTL:      3600"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "STEP-BY-STEP INSTRUCTIONS:"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "1. Open browser and go to: https://ssl.hitme.net.pl/clientarea.php"
echo "2. Login with credentials above"
echo "3. Click 'Domeny' (Domains) or 'Moje Domeny' (My Domains)"
echo "4. Find 'sanbud24.pl' and click 'Zarządzaj' (Manage)"
echo "5. Look for 'DNS' or 'Strefa DNS' (DNS Zone) menu"
echo "6. Click 'Edytuj strefę DNS' (Edit DNS Zone)"
echo "7. Add each record from the table above"
echo "8. Click 'Zapisz' (Save) after adding all records"
echo "9. Wait 5-10 minutes for propagation"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "VERIFICATION AFTER ADDING:"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Run these commands to check if records are added:"
echo ""
echo "  dig www.sanbud24.pl +short"
echo "  dig api.sanbud24.pl +short"
echo "  dig sanbud24.pl TXT +short"
echo "  dig asuid.api.sanbud24.pl TXT +short"
echo ""
echo "Expected results:"
echo "  www → $FRONTEND_URL"
echo "  api → $BACKEND_APP.azurewebsites.net"
echo "  TXT → $VERIFICATION_ID"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "After DNS propagates, run:"
echo "  cd /Users/haos/azure-san-bud"
echo "  ./add-custom-domains.sh"
echo ""
